{
 "title": "Openshift / Cluster Overview",
 "description": "Openshift/K8 Cluster Overview",
 "tags": [
  "overall",
  "cluster"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Resource Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "targets": [
    { "expr": ":node_cpu_utilisation:avg1m" }
   ]
  },
  {
   "title": "Allocatable",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "(avg(node:node_cpu_utilisation:avg1m)*sum(kube_node_status_capacity_cpu_cores)) / sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\"}) / sum(kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "Allocatable",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(avg(node:node_memory_utilisation:)*sum(kube_node_status_capacity_memory_bytes))/sum(kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "Cluster FileSystem Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{device=~\"/dev.*\"}) / sum(avg(node_filesystem_size_bytes{device=~\"/dev/.*\"}) by(device,instance))"
    }
   ]
  },
  {
   "title": "FileSystem Allocatable Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{device=~\".*dockerlv\"}) / sum(avg(\rnode_filesystem_size_bytes{device=~\".*dockerlv\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node:node_cpu_utilisation:avg1m)*sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "Allocatable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(node:node_num_cpu:sum)" }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\"})"
    }
   ]
  },
  {
   "title": "Allocated",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{device=~\".*dockerlv\"})"
    }
   ]
  },
  {
   "title": "CPU Request Allocation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{container!=\"docker-build\"} and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1)) / sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "CPU Limit Allocation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1)) / sum(kube_node_status_allocatable_cpu_cores) "
    }
   ]
  },
  {
   "title": "Memory Request Allocation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{container!=\"docker-build\"} and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1)) / sum(kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "Memory Limit Allocation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes  and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1)) / sum(kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "Total Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{device=~\"/dev/.*\"}) by (device, instance))"
    }
   ]
  },
  {
   "title": "Allocatable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(avg(\rnode_filesystem_size_bytes{device=~\".*dockerlv\"}) by (instance))"
    }
   ]
  },
  { "title": "Node Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Nodes Ready",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": " sum(kube_node_status_condition{status=\"true\",condition=\"Ready\"}) / count(kube_node_info) * 100"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "Master Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_labels{label_node_role_kubernetes_io_master=\"true\"})"
    }
   ]
  },
  {
   "title": "Infra Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_labels{label_node_role_kubernetes_io_infra=\"true\"})"
    }
   ]
  },
  {
   "title": "Compute Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_labels{label_node_role_kubernetes_io_compute=\"true\"})"
    }
   ]
  },
  {
   "title": "Master Nodes",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "max(kube_node_labels{label_node_role_kubernetes_io_master=\"true\"}) by (label_kubernetes_io_hostname)"
    }
   ]
  },
  {
   "title": "Infra Nodes",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 26 },
   "targets": [
    {
     "expr": "max(kube_node_labels{label_node_role_kubernetes_io_infra=\"true\"}) by (label_kubernetes_io_hostname)"
    }
   ]
  },
  {
   "title": "Compute Nodes",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "max(kube_node_labels{label_node_role_kubernetes_io_compute=\"true\"}) by (label_kubernetes_io_hostname)"
    }
   ]
  },
  {
   "title": "Nodes Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(kube_node_status_condition{status=\"true\"}) by (condition)",
     "legendFormat": "{{ condition }}"
    }
   ]
  },
  { "title": "Pod Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Total Running Pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 40 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Total Active Projects",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 40 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_namespace_status_phase{phase=~\"Active\",namespace!~\"^openshift-.+\"})"
    }
   ]
  },
  {
   "title": "Running Pods per Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(sum(kube_pod_status_phase{phase=\"Running\"} !=0) by (namespace,pod) * on (namespace, pod) group_left (node)node_namespace_pod:kube_pod_info:) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Pod Phase across Cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase) by (phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  { "title": "Resource Overview per Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_utilisation:avg1m",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "node:node_memory_utilisation:", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Cluster File System Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(max(node_filesystem_size{fstype=~\"ext[234]|btrfs|xfs|zfs\"} - node_filesystem_avail{fstype=~\"ext[234]|btrfs|xfs|zfs\"}) by (device,pod,namespace)) by (pod,namespace)\n/ scalar(sum(max(node_filesystem_size{fstype=~\"ext[234]|btrfs|xfs|zfs\"}) by (device,pod,namespace)))\n* on (namespace, pod) group_left (node) node_namespace_pod:kube_pod_info:",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Resource Overview per Project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "CPU Core Request Allocation per Project",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short", "label": "core" }
   ],
   "targets": [
    {
     "expr": "sum ((kube_pod_container_resource_requests_cpu_cores)) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Request Allocation per Project",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "decbytes", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum ((kube_pod_container_resource_requests_memory_bytes)) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  }
 ]
}