{
 "title": "Openshift / KubeAPI Metrics",
 "description": "Dashboards to collect apiserver related metrics",
 "tags": [
  "kube-api",
  "api-server latency"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total API Server Request/s [1m]",
   "type": "graph",
   "description": "Returns the average number of apiserver requests over the last minute",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{job=\"apiserver\"}[1m]))",
     "legendFormat": "API server requests"
    }
   ]
  },
  {
   "title": "Total API Server Request/s [1m] per Master Node",
   "type": "graph",
   "description": "Returns the average number of apiserver requests over the last minute per master instance",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{job=\"apiserver\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API Server Request/s  [1m] Verb",
   "type": "graph",
   "description": "Returns the number of API Server Requests grouped by Verb over the last minute.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{job=\"apiserver\",verb!~\"^(?:LIST|WATCH|WATCHLIST|PROXY|CONNECT)$\"}[1m]) ) by (verb)"
    }
   ]
  },
  {
   "title": "API Server Requests/s [1m] Code",
   "type": "graph",
   "description": "Returns the number of API Server Requests grouped by Code over the last  minute.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{job=\"apiserver\",verb!~\"^(?:LIST|WATCH|WATCHLIST|PROXY|CONNECT)$\"}[1m]) ) BY (code)"
    }
   ]
  },
  {
   "title": "APIServer Requests In Flight",
   "type": "graph",
   "description": "The number of concurrent requests to the apiserver",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_current_inflight_requests)",
     "legendFormat": "ApiServer Requests in Flight"
    }
   ]
  },
  {
   "title": "Current APIServer Requests In Flight",
   "type": "singlestat",
   "description": "Current number of concurrent API Server requests",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 26 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(apiserver_current_inflight_requests)"
    }
   ]
  },
  {
   "title": "APIServer Requests In Flight per Master instance",
   "type": "graph",
   "description": "The number of concurrent requests to the apiserver per master instance",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_current_inflight_requests{job=\"apiserver\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API Server Request Latency [1m] POST|GET",
   "type": "graph",
   "description": "Returns the API Server Request Latencies grouped by resource, subresource and verb over the last minute.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_latencies_bucket{job=\"apiserver\",subresource!=\"log\", verb=~\"(POST|GET)\"}[1m])) by (le, resource,subresource, verb))"
    }
   ]
  }
 ]
}