{
 "title": "Openshift / Nodes by Type",
 "description": "Openshift/K8 Cluster Overview",
 "tags": [
  "QoS",
  "node"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "node_type", "label": "Node Type", "query": "master,infra,compute" },
   {
    "name": "nodes",
    "label": "Node",
    "query": "label_values(kube_node_labels{label_node_role_kubernetes_io_$node_type=\"true\"},label_kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Resource Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total CPU Capacity Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(node:node_cpu_utilisation:avg1m{node=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "Total CPU Allocated",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "(avg(node:node_cpu_utilisation:avg1m{node=~\"$nodes\"})*sum(kube_node_status_capacity_cpu_cores{node=~\"$nodes\"})) / sum(kube_node_status_allocatable_cpu_cores{node=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "Total Memory Capacity Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "avg(node:node_memory_utilisation:{node=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "Total Allocated Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(avg(node:node_memory_utilisation:{node=~\"$nodes\"})*sum(kube_node_status_capacity_memory_bytes{node=~\"$nodes\"}))/sum(kube_node_status_allocatable_memory_bytes{node=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "Filesystem Capacity Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(label_replace(container_fs_usage_bytes{device=~\"/dev.*\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")*on(node_ip) group_left(nodename) \r\nlabel_replace(node_uname_info{nodename=~\"$nodes\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")) / sum(sum(avg(label_replace(\r\nnode_filesystem_size_bytes{device=~\"/dev/.*\"},\r\n \"node_ip\",\"$1\",\"instance\",\"(.*):.*\")\r\n*on(node_ip) group_left(nodename) label_replace(\r\nnode_uname_info{nodename=~\"$nodes\"},\r\n\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")) by (device, nodename)) by (nodename))"
    }
   ]
  },
  {
   "title": "FileSystem Allocatable Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "sum(label_replace(container_fs_usage_bytes{device=~\".*dockerlv\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")*on(node_ip) group_left(nodename) \r\nlabel_replace(node_uname_info{nodename=~\"$nodes\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")) / sum(avg(label_replace(\r\nnode_filesystem_size_bytes{device=~\".*dockerlv\"},\r\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")\r\n*on(node_ip) group_left(nodename) label_replace(\r\nnode_uname_info{nodename=~\"$nodes\"},\r\n\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")) by (nodename))"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node:node_cpu_utilisation:avg1m{node=~\"$nodes\"})*sum(kube_node_status_allocatable_cpu_cores{node=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "Allocatable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores{node=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node:node_memory_utilisation:{node=~\"$nodes\"})*sum(kube_node_status_allocatable_memory_bytes{node=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "Allocatable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 7 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_memory_bytes{node=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "Filesystem used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(label_replace(container_fs_usage_bytes{device=~\"/dev.*\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")*on(node_ip) group_left(nodename) \r\nlabel_replace(node_uname_info{nodename=~\"$nodes\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\"))"
    }
   ]
  },
  {
   "title": "Allocated",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(label_replace(container_fs_usage_bytes{device=~\".*dockerlv\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")*on(node_ip) group_left(nodename) \r\nlabel_replace(node_uname_info{nodename=~\"$nodes\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\"))"
    }
   ]
  },
  {
   "title": "CPU Request Commitment",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{container!=\"docker-build\",node=~\"$nodes\"} and on(pod, namespace)( kube_pod_status_phase{ phase!=\"Succeeded\"}==1 and kube_pod_status_phase{ phase!=\"Failed\"}==1)) / sum(kube_node_status_allocatable_cpu_cores{node=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "CPU Limit Commitment",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{node=~\"$nodes\"}  and on(pod, namespace)( kube_pod_status_phase{ phase!=\"Succeeded\"}==1 and kube_pod_status_phase{ phase!=\"Failed\"}==1)) / sum(kube_node_status_allocatable_cpu_cores{node=~\"$nodes\"}) "
    }
   ]
  },
  {
   "title": "Memory Request Commitment",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{container!=\"docker-build\",node=~\"$nodes\"} and on(pod, namespace)( kube_pod_status_phase{ phase!=\"Succeeded\"}==1 and kube_pod_status_phase{ phase!=\"Failed\"}==1)) / sum(kube_node_status_allocatable_memory_bytes{node=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "Memory Limit Commitment",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{node=~\"$nodes\"}  and on(pod, namespace)( kube_pod_status_phase{ phase!=\"Succeeded\"}==1 and kube_pod_status_phase{ phase!=\"Failed\"}==1)) / sum(kube_node_status_allocatable_memory_bytes{node=~\"$nodes\"}) "
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(avg(label_replace(\r\nnode_filesystem_size_bytes{device=~\"/dev/.*\"},\r\n \"node_ip\",\"$1\",\"instance\",\"(.*):.*\")\r\n*on(node_ip) group_left(nodename) label_replace(\r\nnode_uname_info{nodename=~\"$nodes\"},\r\n\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")) by (device, nodename)) by (nodename))"
    }
   ]
  },
  {
   "title": "Allocatable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(label_replace(\r\nnode_filesystem_size_bytes{device=~\".*dockerlv\"},\r\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")\r\n*on(node_ip) group_left(nodename) label_replace(\r\nnode_uname_info{nodename=~\"$nodes\"},\r\n\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")) by (nodename))"
    }
   ]
  },
  { "title": "Node Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Compute Nodes Ready",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": " sum(kube_node_status_condition{status=\"true\",condition=\"Ready\",node=~\"$nodes\"}) / count(kube_node_info{node=~\"$nodes\"}) * 100"
    }
   ]
  },
  {
   "title": "Nodes Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(kube_node_status_condition{status=\"true\",node=~\"$nodes\"}) by (condition)",
     "legendFormat": "{{ condition }}"
    }
   ]
  },
  { "title": "Pod Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Running Pods per Node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(sum(kube_pod_status_phase{phase=\"Running\"} !=0) by (namespace,pod) * on (namespace, pod) group_left (node)node_namespace_pod:kube_pod_info:{node=~\"$nodes\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Total Running Pods",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 24 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(count(sum(kube_pod_status_phase{phase=\"Running\"} !=0) by (namespace,pod) * on (namespace, pod) group_left (node)node_namespace_pod:kube_pod_info:{node=~\"$nodes\"}) by (node))"
    }
   ]
  },
  {
   "title": "Pod Phase across Cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(sum(kube_pod_status_phase{phase=\"Running\"} !=0) by (namespace,pod) * on (namespace, pod) group_left (node)node_namespace_pod:kube_pod_info:{node=~\"$nodes\"}\r\n) by (phase)",
     "legendFormat": "Running"
    },
    {
     "expr": "count(sum(kube_pod_status_phase{phase=\"Succeeded\"} !=0) by (namespace,pod) * on (namespace, pod) group_left (node)node_namespace_pod:kube_pod_info:{node=~\"$nodes\"}\r) by (phase)",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "count(sum(kube_pod_status_phase{phase=\"Failed\"} !=0) by (namespace,pod) * on (namespace, pod) group_left (node)node_namespace_pod:kube_pod_info:{node=~\"$nodes\"}\r) by (phase)",
     "legendFormat": "Failed"
    },
    {
     "expr": "count(sum(kube_pod_status_phase{phase=\"Pending\"} !=0) by (namespace,pod) * on (namespace, pod) group_left (node)node_namespace_pod:kube_pod_info:{node=~\"$nodes\"}\r) by (phase)",
     "legendFormat": "Pending"
    },
    {
     "expr": "count(sum(kube_pod_status_phase{phase=\"Unknown\"} !=0) by (namespace,pod) * on (namespace, pod) group_left (node)node_namespace_pod:kube_pod_info:{node=~\"$nodes\"}\r) by (phase)",
     "legendFormat": "Unknown"
    }
   ]
  },
  { "title": "Resource Overview per Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_utilisation:avg1m{node=~\"$nodes\"}",
     "legendFormat": "Capacity - {{node}}"
    },
    {
     "expr": "((node:node_cpu_utilisation:avg1m{node=~\"$nodes\"}*on(node)kube_node_status_capacity_cpu_cores{node=~\"$nodes\"})/on(node) kube_node_status_allocatable_cpu_cores{node=~\"$nodes\"}) ",
     "legendFormat": "Allocatable - {{node}}"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_memory_utilisation:{node=~\"$nodes\"}",
     "legendFormat": "Capacity - {{node}}"
    },
    {
     "expr": "((node:node_memory_utilisation:{node=~\"$nodes\"}*on(node)kube_node_status_capacity_memory_bytes{node=~\"$nodes\"})/on(node)kube_node_status_allocatable_memory_bytes{node=~\"$nodes\"})",
     "legendFormat": "Allocatable - {{node}}"
    }
   ]
  },
  {
   "title": "File System Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(container_fs_usage_bytes{device=~\".*dockerlv\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")*on(node_ip) group_left(nodename) \r\nlabel_replace(node_uname_info{nodename=~\"$nodes\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")) by (nodename) / avg(label_replace(\r\nnode_filesystem_size_bytes{device=~\".*dockerlv\"},\r\n\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")\r\n*on(node_ip) group_left(nodename) label_replace(\rnode_uname_info{nodename=~\"$nodes\"},\r\n\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")) by (nodename)\n",
     "legendFormat": "Allocatable - {{nodename}}"
    },
    {
     "expr": "sum(label_replace(container_fs_usage_bytes{device=~\"/dev.*\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")*on(node_ip) group_left(nodename) \r\nlabel_replace(node_uname_info{nodename=~\"$nodes\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")) by (nodename) / sum(avg(label_replace(\r\nnode_filesystem_size_bytes{device=~\"/dev/.*\"},\r\n \"node_ip\",\"$1\",\"instance\",\"(.*):.*\")\r\n*on(node_ip) group_left(nodename) label_replace(\r\nnode_uname_info{nodename=~\"$nodes\"},\r\n\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")) by (device, nodename)) by (nodename)\n",
     "legendFormat": "Capacity - {{nodename}}"
    }
   ]
  }
 ]
}