{
 "title": "Openshift / Overall Projects QoS",
 "description": "Shows the overall  CPU/Memory consumption per project",
 "tags": [
  "project",
  "cpu",
  "memory",
  "overall",
  "request",
  "limits"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Overall Project CPU Request",
   "type": "graph",
   "description": "Shows the overall cluster CPU request (cores) per project ",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": " sum(kube_pod_container_resource_requests_cpu_cores and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1)) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Overall Project CPU Limits",
   "type": "graph",
   "description": "Shows the overall cluster CPU limits(cores) per project",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum(kube_pod_container_resource_limits_cpu_cores and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1)) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Overall Project Memory Request",
   "type": "graph",
   "description": "Shows the overall cluster Memoryrequest (cores) per project ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "  sum(kube_pod_container_resource_requests_memory_bytes and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1)) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Overall Project Memory Limit",
   "type": "graph",
   "description": "Shows the overall cluster Memory Limit consumption (GB) per project ",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": " sum(kube_pod_container_resource_limits_memory_bytes and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1)) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}