apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "m-size-limit-range" 
spec:
  limits:
    - type: "Container"
      default:
        cpu: "100m"
        memory: "400Mi"
      defaultRequest:
        cpu: "50m"
        memory: "200Mi"
