== Preface
=== Confidentiality, Copyright, and Disclaimer ===
*Copyright (C) {docdate} {supplier} All Rights Reserved.* 

No part of the work covered by the copyright herein may
be reproduced or used in any form or by any means — graphic, electronic, or mechanical, including photocopying,
recording, taping, or information storage and retrieval systems — without permission in writing from {supplier} except
as is required to share this information as provided with the aforementioned confidential parties.

This document is not a quote and does not include any binding commitments by {supplier}.
If acceptable, a formal quote can be issued upon request, which will include the scope of work, cost, and any customer
requirements as necessary.

=== About This Document

This document is intended as a guide to onboard a new customer to {supplier} managed services. It aims to describe the production of the following components:

- Product Supportability Reports
- MSP Handover
- MSP Onboard & Account creation
- Engagement Journal

