== Product Supportability Reports

Each cluster that is supported by Redhat must have a supportability report. A supportability report runs through a list of checks to check for common errors or unsupported configurations. Examples of such reports can be found on https://drive.google.com/open?id=1GM8BS1KCtI87xJwn4YymuhHb_bLeOA6H[here]. 

=== Generating Reports

The report generation process is semi-automated. There are a lot of improvements to made but for now the process automatically collects data and performs checks on that data. The generation of the report is manual. 

* Clone the git repo that contains the supportability report generator

  git clone git@github.com:crossvale-inc/msp-ocp.git
  # or 
  git clone https://github.com/crossvale-inc/msp-ocp.git

* Change to dir `product-supportability-generator`

* From the bastion node run the `run.yml` playbook using the inventory file for the OCP cluster

  ansible-playbook run.yml -i <inventory>

This will generate a file called `pssa-out.tar.gz` in the `scripts` directory. This file contains a tar file per node containing enough information about the cluster to generate our reports from. 

* Create a file called `nodes.sh` in the `scripts` folder. It should contain 4 variables defining the classification of each node

  MASTERNODES='master1 master2 master3'
  ETCDNODES='master1 master2 master3'
  INFRANODES='infranode1 infranode2'
  NODES='worker1 worker2 worker3'

* Change directory to the `scripts` and extract the `pssa-out.tar.gz` file. 

  tar -xvzf pssa-out.tar.gz

* Change directory to `scripts` and run `extract_master_sos-reports.sh`. Each node's tar file should expand.

Once these steps are complete each check in the `scripts` directory can be executed starting with `check_1_1_rhsm_status.sh`. 

The output of each check must be captured in a document. Use https://drive.google.com/open?id=1Bl8R41qFj0N-rkanWqq5XXr72QuYsm0mKmt0UpdqaQQ[this] document as a template. 

NOTE: Some checks are buggy and not every document check has an associated script. For checks without a script this information can be deduced by exploring the sosreports, accessing the cluster directly or asking the customer. 

=== Operational Procedure Checks

At the tail of the report template is a section to discuss day 2 operations with the customer. We like to have a look into host preparation and installation process (e.g. how/by which tooling are hosts installed), possible configuration management tools used (e.g. chef, puppet,..), as well as understand preparation for the day-2 operations.
Request the following and detail as more information as possible:

- the Installation Procedure used for OpenShift hosts
- the usage of any additional Configuration Management Tools and their purpose
- the Health Checks performed
- the Pruning Strategy implemented
- the Patch Strategy
- the Upgrade Strategy
- the Certificate Management
- the Capacity Management
- the Monitoring of the cluster
- the Backup/Restore procedures implemented
- the Disaster Strategies planned and documented
- the Ansible inventory file used (Make a copy of this file if the customer allows)


