{
 "title": "Openshift / Cluster Overview",
 "description": "Openshift/K8 Cluster Overview",
 "tags": [
  "overall",
  "cluster"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Resource Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "targets": [
    { "expr": ":node_cpu_utilisation:avg1m" }
   ]
  },
  {
   "title": "Allocatable",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "(avg(node:node_cpu_utilisation:avg1m)*sum(kube_node_status_capacity_cpu_cores)) / sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\"}) / sum(kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "Allocatable",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(avg(node:node_memory_utilisation:)*sum(kube_node_status_capacity_memory_bytes))/sum(kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "Cluster FileSystem Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{device=~\"/dev.*\"}) / sum(avg(node_filesystem_size_bytes{device=~\"/dev/.*\"}) by(device,instance))"
    }
   ]
  },
  {
   "title": "FileSystem Allocatable Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{device=~\".*dockerlv\"}) / sum(avg(\rnode_filesystem_size_bytes{device=~\".*dockerlv\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node:node_cpu_utilisation:avg1m)*sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "Allocatable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(node:node_num_cpu:sum)" }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\"})"
    }
   ]
  },
  {
   "title": "Allocated",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{device=~\".*dockerlv\"})"
    }
   ]
  },
  {
   "title": "CPU Request Allocation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{container!=\"docker-build\"} and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1)) / sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "CPU Limit Allocation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1)) / sum(kube_node_status_allocatable_cpu_cores) "
    }
   ]
  },
  {
   "title": "Memory Request Allocation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{container!=\"docker-build\"} and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1)) / sum(kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "Memory Limit Allocation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes  and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1)) / sum(kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "Total Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{device=~\"/dev/.*\"}) by (device, instance))"
    }
   ]
  },
  {
   "title": "Allocatable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(avg(\rnode_filesystem_size_bytes{device=~\".*dockerlv\"}) by (instance))"
    }
   ]
  },
  { "title": "Node Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Nodes Ready",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": " sum(kube_node_status_condition{status=\"true\",condition=\"Ready\"}) / count(kube_node_info) * 100"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "Master Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_labels{label_node_role_kubernetes_io_master=\"true\"})"
    }
   ]
  },
  {
   "title": "Infra Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_labels{label_node_role_kubernetes_io_infra=\"true\"})"
    }
   ]
  },
  {
   "title": "Compute Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_labels{label_node_role_kubernetes_io_compute=\"true\"})"
    }
   ]
  },
  {
   "title": "Master Nodes",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "max(kube_node_labels{label_node_role_kubernetes_io_master=\"true\"}) by (label_kubernetes_io_hostname)"
    }
   ]
  },
  {
   "title": "Infra Nodes",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 26 },
   "targets": [
    {
     "expr": "max(kube_node_labels{label_node_role_kubernetes_io_infra=\"true\"}) by (label_kubernetes_io_hostname)"
    }
   ]
  },
  {
   "title": "Compute Nodes",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "max(kube_node_labels{label_node_role_kubernetes_io_compute=\"true\"}) by (label_kubernetes_io_hostname)"
    }
   ]
  },
  {
   "title": "Nodes Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(kube_node_status_condition{status=\"true\"}) by (condition)",
     "legendFormat": "{{ condition }}"
    }
   ]
  },
  { "title": "Pod Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Total Running Pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 40 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Total Active Projects",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 40 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_namespace_status_phase{phase=~\"Active\",namespace!~\"^openshift-.+\"})"
    }
   ]
  },
  {
   "title": "Running Pods per Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(sum(kube_pod_status_phase{phase=\"Running\"} !=0) by (namespace,pod) * on (namespace, pod) group_left (node)node_namespace_pod:kube_pod_info:) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Pod Phase across Cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase) by (phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  { "title": "Resource Overview per Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_utilisation:avg1m",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "node:node_memory_utilisation:", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Cluster File System Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(max(node_filesystem_size{fstype=~\"ext[234]|btrfs|xfs|zfs\"} - node_filesystem_avail{fstype=~\"ext[234]|btrfs|xfs|zfs\"}) by (device,pod,namespace)) by (pod,namespace)\n/ scalar(sum(max(node_filesystem_size{fstype=~\"ext[234]|btrfs|xfs|zfs\"}) by (device,pod,namespace)))\n* on (namespace, pod) group_left (node) node_namespace_pod:kube_pod_info:",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Resource Overview per Project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "CPU Core Request Allocation per Project",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short", "label": "core" }
   ],
   "targets": [
    {
     "expr": "sum ((kube_pod_container_resource_requests_cpu_cores)) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Request Allocation per Project",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "decbytes", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum ((kube_pod_container_resource_requests_memory_bytes)) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  }
 ]
}
{
 "title": "Openshift / KubeAPI Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total API Server Request/s [1m]",
   "type": "graph",
   "description": "Returns the average number of apiserver requests over the last minute",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{job=\"apiserver\"}[1m]))",
     "legendFormat": "API server requests"
    }
   ]
  },
  {
   "title": "Total API Server Request/s [1m] per Master Node",
   "type": "graph",
   "description": "Returns the average number of apiserver requests over the last minute per master instance",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{job=\"apiserver\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API Server Request/s  [1m] Verb",
   "type": "graph",
   "description": "Returns the number of API Server Requests grouped by Verb over the last minute.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{job=\"apiserver\",verb!~\"^(?:LIST|WATCH|WATCHLIST|PROXY|CONNECT)$\"}[1m]) ) by (verb)"
    }
   ]
  },
  {
   "title": "API Server Requests/s [1m] Code",
   "type": "graph",
   "description": "Returns the number of API Server Requests grouped by Code over the last  minute.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{job=\"apiserver\",verb!~\"^(?:LIST|WATCH|WATCHLIST|PROXY|CONNECT)$\"}[1m]) ) BY (code)"
    }
   ]
  },
  {
   "title": "APIServer Requests In Flight",
   "type": "graph",
   "description": "The number of concurrent requests to the apiserver",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_current_inflight_requests)",
     "legendFormat": "ApiServer Requests in Flight"
    }
   ]
  },
  {
   "title": "Current APIServer Requests In Flight",
   "type": "singlestat",
   "description": "Current number of concurrent API Server requests",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 26 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(apiserver_current_inflight_requests)"
    }
   ]
  },
  {
   "title": "APIServer Requests In Flight per Master instance",
   "type": "graph",
   "description": "The number of concurrent requests to the apiserver per master instance",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_current_inflight_requests{job=\"apiserver\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API Server Request Latency [1m] POST|GET",
   "type": "graph",
   "description": "Returns the API Server Request Latencies grouped by resource, subresource and verb over the last minute.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_latencies_bucket{job=\"apiserver\",subresource!=\"log\", verb=~\"(POST|GET)\"}[1m])) by (le, resource,subresource, verb))"
    }
   ]
  }
 ]
}
{
 "title": "OpenShift / Namespace",
 "tags": [
  "namespace ",
  "cpu",
  "memory"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Namespace Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage by pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage by pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", container_name!=\"\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"}  and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1)) ",
     "legendFormat": "Limit"
    },
    {
     "expr": " sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"})",
     "legendFormat": "Usage "
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}  and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1))",
     "legendFormat": "Request "
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "3" }
   ],
   "targets": [
    {
     "expr": " sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"}  and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1)) \r",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=\"$namespace\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": " sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}  and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Ephemeral Storage Usage",
   "type": "graph",
   "description": "In addition to persistent storage, pods and containers may require ephemeral or transient local storage for their operation. The lifetime of this ephemeral storage does not extend beyond the life of the individual pod, and this ephemeral storage cannot be shared across pods.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"$namespace\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "CPU Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"}) by (pod)"
    }
   ]
  },
  { "title": "Memory Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"}) by (pod)"
    }
   ]
  }
 ]
}
{
 "title": "OpenShift / Node",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(kube_node_info, node)"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_utilisation:avg1m{node=\"$node\"}",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "CPU Saturation (Load1)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_saturation_load1:{node=\"$node\"}",
     "legendFormat": "Saturation"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_memory_utilisation:{node=\"$node\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Memory Saturation (Swap I/O)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_memory_swap_io_bytes:sum_rate{node=\"$node\"}",
     "legendFormat": "Swap IO"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Disk IO Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_disk_utilisation:avg_irate{node=\"$node\"}",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Disk IO Saturation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_disk_saturation:avg_irate{node=\"$node\"}",
     "legendFormat": "Saturation"
    }
   ]
  },
  { "title": "Net", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Net Utilisation (Transmitted)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_net_utilisation:sum_irate{node=\"$node\"}",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Net Saturation (Dropped)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_net_saturation:sum_irate{node=\"$node\"}",
     "legendFormat": "Saturation"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Disk Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_filesystem_usage:\n* on (namespace, pod) group_left (node) node_namespace_pod:kube_pod_info:{node=\"$node\"}\n",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}
{
 "title": "Openshift / Nodes by Type",
 "description": "Openshift/K8 Cluster Overview",
 "tags": [
  "QoS",
  "node"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "node_type", "label": "Node Type", "query": "master,infra,compute" },
   {
    "name": "nodes",
    "label": "Node",
    "query": "label_values(kube_node_labels{label_node_role_kubernetes_io_$node_type=\"true\"},label_kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Resource Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total CPU Capacity Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(node:node_cpu_utilisation:avg1m{node=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "Total CPU Allocated",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "(avg(node:node_cpu_utilisation:avg1m{node=~\"$nodes\"})*sum(kube_node_status_capacity_cpu_cores{node=~\"$nodes\"})) / sum(kube_node_status_allocatable_cpu_cores{node=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "Total Memory Capacity Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "avg(node:node_memory_utilisation:{node=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "Total Allocated Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(avg(node:node_memory_utilisation:{node=~\"$nodes\"})*sum(kube_node_status_capacity_memory_bytes{node=~\"$nodes\"}))/sum(kube_node_status_allocatable_memory_bytes{node=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "Filesystem Capacity Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(label_replace(container_fs_usage_bytes{device=~\"/dev.*\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")*on(node_ip) group_left(nodename) \r\nlabel_replace(node_uname_info{nodename=~\"$nodes\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")) / sum(sum(avg(label_replace(\r\nnode_filesystem_size_bytes{device=~\"/dev/.*\"},\r\n \"node_ip\",\"$1\",\"instance\",\"(.*):.*\")\r\n*on(node_ip) group_left(nodename) label_replace(\r\nnode_uname_info{nodename=~\"$nodes\"},\r\n\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")) by (device, nodename)) by (nodename))"
    }
   ]
  },
  {
   "title": "FileSystem Allocatable Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "sum(label_replace(container_fs_usage_bytes{device=~\".*dockerlv\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")*on(node_ip) group_left(nodename) \r\nlabel_replace(node_uname_info{nodename=~\"$nodes\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")) / sum(avg(label_replace(\r\nnode_filesystem_size_bytes{device=~\".*dockerlv\"},\r\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")\r\n*on(node_ip) group_left(nodename) label_replace(\r\nnode_uname_info{nodename=~\"$nodes\"},\r\n\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")) by (nodename))"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node:node_cpu_utilisation:avg1m{node=~\"$nodes\"})*sum(kube_node_status_allocatable_cpu_cores{node=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "Allocatable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores{node=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node:node_memory_utilisation:{node=~\"$nodes\"})*sum(kube_node_status_allocatable_memory_bytes{node=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "Allocatable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 7 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_memory_bytes{node=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "Filesystem used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(label_replace(container_fs_usage_bytes{device=~\"/dev.*\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")*on(node_ip) group_left(nodename) \r\nlabel_replace(node_uname_info{nodename=~\"$nodes\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\"))"
    }
   ]
  },
  {
   "title": "Allocated",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(label_replace(container_fs_usage_bytes{device=~\".*dockerlv\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")*on(node_ip) group_left(nodename) \r\nlabel_replace(node_uname_info{nodename=~\"$nodes\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\"))"
    }
   ]
  },
  {
   "title": "CPU Request Commitment",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{container!=\"docker-build\",node=~\"$nodes\"} and on(pod, namespace)( kube_pod_status_phase{ phase!=\"Succeeded\"}==1 and kube_pod_status_phase{ phase!=\"Failed\"}==1)) / sum(kube_node_status_allocatable_cpu_cores{node=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "CPU Limit Commitment",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{node=~\"$nodes\"}  and on(pod, namespace)( kube_pod_status_phase{ phase!=\"Succeeded\"}==1 and kube_pod_status_phase{ phase!=\"Failed\"}==1)) / sum(kube_node_status_allocatable_cpu_cores{node=~\"$nodes\"}) "
    }
   ]
  },
  {
   "title": "Memory Request Commitment",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{container!=\"docker-build\",node=~\"$nodes\"} and on(pod, namespace)( kube_pod_status_phase{ phase!=\"Succeeded\"}==1 and kube_pod_status_phase{ phase!=\"Failed\"}==1)) / sum(kube_node_status_allocatable_memory_bytes{node=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "Memory Limit Commitment",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{node=~\"$nodes\"}  and on(pod, namespace)( kube_pod_status_phase{ phase!=\"Succeeded\"}==1 and kube_pod_status_phase{ phase!=\"Failed\"}==1)) / sum(kube_node_status_allocatable_memory_bytes{node=~\"$nodes\"}) "
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(avg(label_replace(\r\nnode_filesystem_size_bytes{device=~\"/dev/.*\"},\r\n \"node_ip\",\"$1\",\"instance\",\"(.*):.*\")\r\n*on(node_ip) group_left(nodename) label_replace(\r\nnode_uname_info{nodename=~\"$nodes\"},\r\n\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")) by (device, nodename)) by (nodename))"
    }
   ]
  },
  {
   "title": "Allocatable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(label_replace(\r\nnode_filesystem_size_bytes{device=~\".*dockerlv\"},\r\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")\r\n*on(node_ip) group_left(nodename) label_replace(\r\nnode_uname_info{nodename=~\"$nodes\"},\r\n\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")) by (nodename))"
    }
   ]
  },
  { "title": "Node Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Compute Nodes Ready",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": " sum(kube_node_status_condition{status=\"true\",condition=\"Ready\",node=~\"$nodes\"}) / count(kube_node_info{node=~\"$nodes\"}) * 100"
    }
   ]
  },
  {
   "title": "Nodes Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(kube_node_status_condition{status=\"true\",node=~\"$nodes\"}) by (condition)",
     "legendFormat": "{{ condition }}"
    }
   ]
  },
  { "title": "Pod Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Running Pods per Node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(sum(kube_pod_status_phase{phase=\"Running\"} !=0) by (namespace,pod) * on (namespace, pod) group_left (node)node_namespace_pod:kube_pod_info:{node=~\"$nodes\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Total Running Pods",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 24 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(count(sum(kube_pod_status_phase{phase=\"Running\"} !=0) by (namespace,pod) * on (namespace, pod) group_left (node)node_namespace_pod:kube_pod_info:{node=~\"$nodes\"}) by (node))"
    }
   ]
  },
  {
   "title": "Pod Phase across Cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(sum(kube_pod_status_phase{phase=\"Running\"} !=0) by (namespace,pod) * on (namespace, pod) group_left (node)node_namespace_pod:kube_pod_info:{node=~\"$nodes\"}\r\n) by (phase)",
     "legendFormat": "Running"
    },
    {
     "expr": "count(sum(kube_pod_status_phase{phase=\"Succeeded\"} !=0) by (namespace,pod) * on (namespace, pod) group_left (node)node_namespace_pod:kube_pod_info:{node=~\"$nodes\"}\r) by (phase)",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "count(sum(kube_pod_status_phase{phase=\"Failed\"} !=0) by (namespace,pod) * on (namespace, pod) group_left (node)node_namespace_pod:kube_pod_info:{node=~\"$nodes\"}\r) by (phase)",
     "legendFormat": "Failed"
    },
    {
     "expr": "count(sum(kube_pod_status_phase{phase=\"Pending\"} !=0) by (namespace,pod) * on (namespace, pod) group_left (node)node_namespace_pod:kube_pod_info:{node=~\"$nodes\"}\r) by (phase)",
     "legendFormat": "Pending"
    },
    {
     "expr": "count(sum(kube_pod_status_phase{phase=\"Unknown\"} !=0) by (namespace,pod) * on (namespace, pod) group_left (node)node_namespace_pod:kube_pod_info:{node=~\"$nodes\"}\r) by (phase)",
     "legendFormat": "Unknown"
    }
   ]
  },
  { "title": "Resource Overview per Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_utilisation:avg1m{node=~\"$nodes\"}",
     "legendFormat": "Capacity - {{node}}"
    },
    {
     "expr": "((node:node_cpu_utilisation:avg1m{node=~\"$nodes\"}*on(node)kube_node_status_capacity_cpu_cores{node=~\"$nodes\"})/on(node) kube_node_status_allocatable_cpu_cores{node=~\"$nodes\"}) ",
     "legendFormat": "Allocatable - {{node}}"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_memory_utilisation:{node=~\"$nodes\"}",
     "legendFormat": "Capacity - {{node}}"
    },
    {
     "expr": "((node:node_memory_utilisation:{node=~\"$nodes\"}*on(node)kube_node_status_capacity_memory_bytes{node=~\"$nodes\"})/on(node)kube_node_status_allocatable_memory_bytes{node=~\"$nodes\"})",
     "legendFormat": "Allocatable - {{node}}"
    }
   ]
  },
  {
   "title": "File System Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(container_fs_usage_bytes{device=~\".*dockerlv\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")*on(node_ip) group_left(nodename) \r\nlabel_replace(node_uname_info{nodename=~\"$nodes\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")) by (nodename) / avg(label_replace(\r\nnode_filesystem_size_bytes{device=~\".*dockerlv\"},\r\n\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")\r\n*on(node_ip) group_left(nodename) label_replace(\rnode_uname_info{nodename=~\"$nodes\"},\r\n\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")) by (nodename)\n",
     "legendFormat": "Allocatable - {{nodename}}"
    },
    {
     "expr": "sum(label_replace(container_fs_usage_bytes{device=~\"/dev.*\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")*on(node_ip) group_left(nodename) \r\nlabel_replace(node_uname_info{nodename=~\"$nodes\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")) by (nodename) / sum(avg(label_replace(\r\nnode_filesystem_size_bytes{device=~\"/dev/.*\"},\r\n \"node_ip\",\"$1\",\"instance\",\"(.*):.*\")\r\n*on(node_ip) group_left(nodename) label_replace(\r\nnode_uname_info{nodename=~\"$nodes\"},\r\n\"node_ip\",\"$1\",\"instance\",\"(.*):.*\")) by (device, nodename)) by (nodename)\n",
     "legendFormat": "Capacity - {{nodename}}"
    }
   ]
  }
 ]
}
{
 "title": "Openshift / Overall Projects Consumption",
 "description": "Shows the overall  CPU/Memory consumption per project",
 "tags": [
  "project",
  "cpu",
  "memory",
  "overall"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Overall Project CPU Consumption",
   "type": "graph",
   "description": "Shows the overall cluster CPU consumption (cores) per project ",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Overall Project Memory Consumption",
   "type": "graph",
   "description": "Shows the overall cluster Memory consumption (GB) per project ",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "namespace:container_memory_usage_bytes:sum",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}
{
 "title": "Openshift / Overall Projects QoS",
 "description": "Shows the overall  CPU/Memory consumption per project",
 "tags": [
  "project",
  "cpu",
  "memory",
  "overall",
  "request",
  "limits"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Overall Project CPU Request",
   "type": "graph",
   "description": "Shows the overall cluster CPU request (cores) per project ",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": " sum(kube_pod_container_resource_requests_cpu_cores and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1)) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Overall Project CPU Limits",
   "type": "graph",
   "description": "Shows the overall cluster CPU limits(cores) per project",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum(kube_pod_container_resource_limits_cpu_cores and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1)) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Overall Project Memory Request",
   "type": "graph",
   "description": "Shows the overall cluster Memoryrequest (cores) per project ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "  sum(kube_pod_container_resource_requests_memory_bytes and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1)) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Overall Project Memory Limit",
   "type": "graph",
   "description": "Shows the overall cluster Memory Limit consumption (GB) per project ",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": " sum(kube_pod_container_resource_limits_memory_bytes and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1)) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}
{
 "title": "OpenShift / Pod",
 "tags": [ "pod" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\", container_name!=\"\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=\"$pod\"}  and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1)) ",
     "legendFormat": "Limit"
    },
    {
     "expr": " sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\",pod_name=\"$pod\"})",
     "legendFormat": "Usage "
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=\"$pod\"}  and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1))",
     "legendFormat": "Request "
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "3" }
   ],
   "targets": [
    {
     "expr": " sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=\"$pod\"}  and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1)) \r",
     "legendFormat": "Limit"
    },
    {
     "expr": "pod_name:container_memory_usage_bytes:sum{namespace=\"$namespace\",pod_name=\"$pod\"}",
     "legendFormat": "Usage"
    },
    {
     "expr": " sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=\"$pod\"}  and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Ephemeral Storage Usage",
   "type": "graph",
   "description": "In addition to persistent storage, pods and containers may require ephemeral or transient local storage for their operation. The lifetime of this ephemeral storage does not extend beyond the life of the individual pod, and this ephemeral storage cannot be shared across pods.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{pod_name=\"$pod\",container_name!=\"POD\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "CPU Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod_name=\"$pod\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod_name=\"$pod\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    }
   ]
  },
  { "title": "Memory Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\", container_name!=\"\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=\"$pod\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=\"$pod\", container_name!=\"\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    }
   ]
  }
 ]
}
{
 "title": "Openshift / Projects Resources",
 "description": "Display usage of ResourceQuota by namespace in OCP cluster.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "CPU Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Allocated / Requests Quota (CPU)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"requests.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Limits Allocated / Limits Quota (CPU)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (kube_resourcequota{resource=\"limits.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Current Usage / Request Quota (CPU)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[1m])) / sum(kube_resourcequota{resource=\"requests.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Current Usage / Limits Quota (CPU)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[1m])) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", resource=\"limits.cpu\", type=\"hard\"}",
     "legendFormat": "CPU Quota Limits"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", resource=\"requests.cpu\", type=\"hard\"}",
     "legendFormat": "CPU Quota Requests"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", resource=\"limits.cpu\", type=\"used\"}",
     "legendFormat": "CPU Allocated Limits"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", resource=\"requests.cpu\", type=\"used\"}",
     "legendFormat": "CPU Allocated Requests"
    }
   ]
  },
  { "title": "Memory Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Requests Allocated / Requests Quota (Memory)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (kube_resourcequota{resource=\"requests.memory\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"requests.memory\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Limits Allocated / Limits Quota (Memory)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 14 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (kube_resourcequota{resource=\"limits.memory\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.memory\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Current Usage / Request Quota (Memory)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 14 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\", namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"requests.memory\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Current Usage / Limits Quota (Memory)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 14 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\", namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.memory\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\", namespace=\"$namespace\"})",
     "legendFormat": "Actual Usage"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", resource=\"limits.memory\", type=\"hard\"}",
     "legendFormat": "Memory Quota Limits"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", resource=\"requests.memory\", type=\"hard\"}",
     "legendFormat": "Memory Quota Requests"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", resource=\"limits.memory\", type=\"used\"}",
     "legendFormat": "Memory Allocated Limits"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", resource=\"requests.memory\", type=\"used\"}",
     "legendFormat": "Memory Allocated Requests"
    }
   ]
  }
 ]
}
{
 "title": "OpenShift / Namespace",
 "tags": [
  "namespace ",
  "cpu",
  "memory"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Project",
    "query": "label_values(kube_pod_info{namespace!~\"^openshift-.+|^prometheus|^cluster-monit.+|default|trident|kube-system\"}, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Namespace Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage by pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage by pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", container_name!=\"\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"}  and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1)) ",
     "legendFormat": "Limit"
    },
    {
     "expr": " sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"})",
     "legendFormat": "Usage "
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}  and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1))",
     "legendFormat": "Request "
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "3" }
   ],
   "targets": [
    {
     "expr": " sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"}  and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1)) \r",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=\"$namespace\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": " sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}  and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Ephemeral Storage Usage",
   "type": "graph",
   "description": "In addition to persistent storage, pods and containers may require ephemeral or transient local storage for their operation. The lifetime of this ephemeral storage does not extend beyond the life of the individual pod, and this ephemeral storage cannot be shared across pods.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"$namespace\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "CPU Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"}) by (pod)"
    }
   ]
  },
  { "title": "Memory Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"}) by (pod)"
    }
   ]
  }
 ]
}
{
 "title": "OpenShift / Pod",
 "tags": [ "pod" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info{namespace!~\"^openshift-.+|^prometheus|^cluster-monit.+|default|trident|kube-system\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\", container_name!=\"\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=\"$pod\"}  and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1)) ",
     "legendFormat": "Limit"
    },
    {
     "expr": " sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\",pod_name=\"$pod\"})",
     "legendFormat": "Usage "
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=\"$pod\"}  and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1))",
     "legendFormat": "Request "
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "3" }
   ],
   "targets": [
    {
     "expr": " sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=\"$pod\"}  and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1)) \r",
     "legendFormat": "Limit"
    },
    {
     "expr": "pod_name:container_memory_usage_bytes:sum{namespace=\"$namespace\",pod_name=\"$pod\"}",
     "legendFormat": "Usage"
    },
    {
     "expr": " sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=\"$pod\"}  and on(pod, namespace)(kube_pod_status_phase{phase=\"Running\"}==1))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Ephemeral Storage Usage",
   "type": "graph",
   "description": "In addition to persistent storage, pods and containers may require ephemeral or transient local storage for their operation. The lifetime of this ephemeral storage does not extend beyond the life of the individual pod, and this ephemeral storage cannot be shared across pods.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{pod_name=\"$pod\",container_name!=\"POD\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "CPU Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod_name=\"$pod\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod_name=\"$pod\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    }
   ]
  },
  { "title": "Memory Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\", container_name!=\"\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=\"$pod\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=\"$pod\", container_name!=\"\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    }
   ]
  }
 ]
}