apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "s-size-limit-range" 
spec:
  limits:
    - type: "Container"
      default:
        cpu: "50m"
        memory: "100Mi"
      defaultRequest:
        cpu: "25m"
        memory: "50Mi"
