#!/bin/bash

# Created by Carlos M. Arias
# This scripts facilitates login in OCP clusters in Apria

if [[ $1 -eq null  ]]  || [[ -z $2 ]]
then
        echo "Missing or wrong arguments"
        echo ""
        echo "Usage: oclogin [ 3|4 ] [ username ]"
        exit 1
fi

BASTION=$(hostname)

case $BASTION in
        labinstaller)
                OCP3_SERVER='https://ocp-master-lab.apria.com:443'
                OCP4_SERVER='https://api.ocp4-lab.internal:6443'
        ;;
        nonprodinstaller)
                OCP3_SERVER='https://gocp-master-np.apria.com:443'
                OCP4_SERVER='https://api.ocp4-np.internal:6443'
        ;;
        prodinstaller)
                OCP3_SERVER='https://gocp-master.apria.com:443'
                OCP4_SERVER='https://api.ocp4-prod.internal:6443'
        ;;
esac

if [[ $1 -eq 3  ]]
then
        oc login $OCP3_SERVER -u $2
        exit 0

elif [[ $1 -eq 4  ]]
then
        oc login --server=$OCP4_SERVER -u $2
        exit 0
else
        echo "Wrong OCP version number. Choose 3 or 4"
        exit 1
fi

