- archive:
    path:
      - /etc/etcd/*
      - /var/tmp/pssa/tmp/*
    dest: "/var/tmp/pssa/pssa-{{inventory_hostname}}/{{inventory_hostname}}-etcd.tar"
    exclude_path:
      - /etc/etcd/*key
      - /etc/etcd/*crt
      - /etc/etcd/ca
      - /etc/etcd/server.csr
      - /etc/etcd/peer.csr
      - /etc/etcd/generated_certs
