---
- hosts:
  - nodes
  - etcd
  - localhost
  - glusterfs
  - glusterfs_registry
  gather_facts: no
  tasks:
  - name: create pssa temp directory on all hosts
    file:
      path: "/var/tmp/pssa/{{item}}"
      mode: 0755
      state: directory
    with_items: ["pssa-{{inventory_hostname}}","tmp"]

- hosts: masters
  gather_facts: no
  tasks:
   - name: get ocp major version on all master hosts
     shell: rpm -qa atomic-openshift-node |awk -F - '{print $4}'|cut -d . -f 1
     args:
        warn: false
     register: ocp_maj_ver
     changed_when: false
   - name: setting fact ocp_maj_ver_fact globally
     set_fact:
        ocp_maj_ver_fact : "{{ ocp_maj_ver.stdout }}"

   - name: get ocp minor version on all master hosts
     shell: rpm -qa atomic-openshift-node |awk -F - '{print $4}'|cut -d . -f 2
     args:
        warn: false
     register: ocp_min_ver
     changed_when: false
   - name: setting fact ocp_min_ver_fact globally
     set_fact: 
        ocp_min_ver_fact : "{{ ocp_min_ver.stdout }}"

- hosts: all
  gather_facts: no
  tasks:
   - name: get sos major version on all hosts
     shell: rpm -qa sos |awk -F - '{print $2}'|cut -d . -f 1
     args:
       warn: false
     register: sos_maj_ver
     changed_when: False
   - name: setting fact sos_maj_ver_fact  globally
     set_fact: 
        sos_maj_ver_fact : "{{ sos_maj_ver.stdout }}"

   - name: get sos minor version on all hosts
     shell: rpm -qa sos |awk -F - '{print $2}'|cut -d . -f 2
     args:
       warn: false
     register: sos_min_ver
     changed_when: False
   - name: setting fact sos_min_ver_fact  globally
     set_fact:
        sos_min_ver_fact : "{{ sos_min_ver.stdout }}"

- hosts: masters:&etcd
  gather_facts: no
  tasks:
  - name: run master collection script on masters with colocated etcd
    script: data-collection-scripts/master-commands.sh

  - name: run etcd collection script for colocated rpm-based etcd 
    script: data-collection-scripts/etcd-commands.sh
    when:  ocp_maj_ver_fact|int == 3 and ocp_min_ver_fact|int < 10

  - name: copy over etcd collection script to masters with colocated etcd 
    copy:
      src: data-collection-scripts/etcd-commands.sh
      dest: /var/tmp/pssa/etcd-commands.sh
    when: ocp_maj_ver_fact|int == 3 and ocp_min_ver_fact|int >= 10

  - name: run etcd collection script for colocated etcd in a container
    script: data-collection-scripts/etcd-static-container-collector.sh
    when: ocp_maj_ver_fact|int == 3 and ocp_min_ver_fact|int >= 10

  - name: run ocs collection script
    script: data-collection-scripts/check-ocs-commands.sh
    run_once: true

  - name: archive data from masters and colocated etcd
    archive:
      path:
        - /etc/etcd/*
        - /etc/origin/master/*
        - /etc/origin/node/*
        - /var/tmp/pssa/tmp/*
      dest: "/var/tmp/pssa/pssa-{{inventory_hostname}}/{{inventory_hostname}}-master-etcd.tar"
      exclude_path:
        - /etc/origin/master/*.key
        - /etc/origin/master/*.crt
        - /etc/origin/master/named_certificates
        - /etc/origin/master/master.etcd-client.csr
        - /etc/origin/master/htpasswd*
        - /etc/origin/node/*.key
        - /etc/origin/node/*.crt
        - /etc/etcd/*.key
        - /etc/etcd/*.crt
        - /etc/etcd/ca
        - /etc/etcd/server.csr
        - /etc/etcd/peer.csr
        - /etc/etcd/generated_certs

- hosts: masters:!etcd
  gather_facts: no
  tasks:
  - name: run master collection script on standalone masters
    script: data-collection-scripts/master-commands.sh

  - name: run ocs collection script
    script: data-collection-scripts/check-ocs-commands.sh
    run_once: true

  - name: archive data from masters without etcd colocated
    archive:
      path:
        - /etc/origin/master/*
        - /etc/origin/node/*
        - /var/tmp/pssa/tmp/*
      dest: "/var/tmp/pssa/pssa-{{inventory_hostname}}/{{inventory_hostname}}-master.tar"
      exclude_path:
        - /etc/origin/master/*.key
        - /etc/origin/master/*.crt
        - /etc/origin/master/named_certificates
        - /etc/origin/master/master.etcd-client.csr
        - /etc/origin/master/htpasswd*
        - /etc/origin/node/*.key
        - /etc/origin/node/*.crt

- hosts: etcd:!masters
  gather_facts: no
  tasks:
  - name: run etcd collection script for standalone rpm-based etcd
    script: data-collection-scripts/etcd-commands.sh
    when:  ocp_maj_ver_fact|int == 3 and ocp_min_ver_fact|int < 10

  - name: copy over etcd collection script to standalone etcd (cont)
    copy:
      src: data-collection-scripts/etcd-commands.sh
      dest: /var/tmp/pssa/etcd-commands.sh
    when: ocp_maj_ver_fact|int == 3 and ocp_min_ver_fact|int >= 10

  - name: run etcd collection script for standalone etcd (cont)
    script: data-collection-scripts/etcd-static-container-collector.sh
    when: ocp_maj_ver_fact|int == 3 and ocp_min_ver_fact|int >= 10

  - name: archive data from standalone etcd
    archive:
      path:
        - /etc/etcd/*
        - /var/tmp/pssa/tmp/*
      dest: "/var/tmp/pssa/pssa-{{inventory_hostname}}/{{inventory_hostname}}-etcd.tar"
      exclude_path:
        - /etc/etcd/*.key
        - /etc/etcd/*.crt
        - /etc/etcd/ca
        - /etc/etcd/server.csr
        - /etc/etcd/peer.csr
        - /etc/etcd/generated_certs

- hosts: 
  - nodes:!masters
  gather_facts: no
  tasks:
  - name: archive data from nodes
    archive:
      path:
        - /etc/origin/node/*
      dest: "/var/tmp/pssa/pssa-{{inventory_hostname}}/{{inventory_hostname}}-node.tar"
      exclude_path:
        - /etc/origin/node/*.key
        - /etc/origin/node/*.crt

- hosts: 
  - nodes
  - glusterfs
  - glusterfs_registry
  gather_facts: no
  tasks:
  - name: run sosreport on all nodes with sosreport < 3.6
    command: sosreport --batch -o  auditd,block,cgroups,chrony,cron,devicemapper,devices,docker,etcd,filesys,general,gluster,hardware,kernel,kubernetes,memory,networking,networkmanager,nfs,openvswitch,process,processor,rpm,scsi,selinux,services,subscription_manager,system,systemd,tuned,xfs,yum,atomichost,ntp --tmp-dir /var/tmp/pssa/pssa-{{inventory_hostname}} --name {{inventory_hostname}}
    when: sos_maj_ver_fact|int == 3 and sos_min_ver_fact|int < 6

  - name: run sosreport on all nodes with sosreport >= 3.6
    command: sosreport --batch -o  auditd,block,cgroups,chrony,cron,devicemapper,devices,docker,etcd,filesys,gluster,hardware,host,kernel,kubernetes,logs,memory,networking,networkmanager,nfs,openvswitch,process,processor,release,rpm,scsi,selinux,services,subscription_manager,system,systemd,tuned,xfs,yum,atomichost,ntp,gluster,gluster_block,iscsi,iscsitarget --tmp-dir /var/tmp/pssa/pssa-{{inventory_hostname}} --name {{inventory_hostname}}
    when: sos_maj_ver_fact|int == 3 and sos_min_ver_fact|int >= 6

  - name: tar pssa folder
    archive:
      path: /var/tmp/pssa/pssa-{{inventory_hostname}}
      dest: "/var/tmp/pssa/{{inventory_hostname}}.tar"
      remove: yes

  - name: copy files to localhost
    fetch:
      src:  "/var/tmp/pssa/{{inventory_hostname}}.tar"
      dest: /var/tmp/pssa/tmp/
      flat: yes

- hosts: etcd:!masters
  gather_facts: no
  tasks:
  - name: run sosreport on all external etcd with sosreport < 3.6
    command: sosreport --batch -o  auditd,block,cgroups,chrony,cron,devicemapper,devices,docker,etcd,filesys,general,gluster,hardware,kernel,kubernetes,memory,networking,networkmanager,nfs,openvswitch,process,processor,rpm,scsi,selinux,services,subscription_manager,system,systemd,tuned,xfs,yum,atomichost,ntp,gluster,gluster_block,iscsi,iscsitarget --tmp-dir /var/tmp/pssa/pssa-{{inventory_hostname}} --name {{inventory_hostname}}
    when: sos_maj_ver_fact|int == 3 and sos_min_ver_fact|int < 6

  - name: run sosreport on all external etcd with sosreport >= 3.6
    command: sosreport --batch -o  auditd,block,cgroups,chrony,cron,devicemapper,devices,docker,etcd,filesys,gluster,hardware,host,kernel,kubernetes,logs,memory,networking,networkmanager,nfs,openvswitch,process,processor,release,rpm,scsi,selinux,services,subscription_manager,system,systemd,tuned,xfs,yum,atomichost,ntp --tmp-dir /var/tmp/pssa/pssa-{{inventory_hostname}} --name {{inventory_hostname}}
    when: sos_maj_ver_fact|int == 3 and sos_min_ver_fact|int >= 6

  - name: tar pssa folder
    archive:
      path: /var/tmp/pssa/pssa-{{inventory_hostname}}
      dest: "/var/tmp/pssa/{{inventory_hostname}}.tar"
      remove: yes

  - name: copy files to localhost
    fetch:
      src:  "/var/tmp/pssa/{{inventory_hostname}}.tar"
      dest: /var/tmp/pssa/tmp/
      flat: yes

- hosts: localhost
  gather_facts: no
  tasks:
  - name: copy ansible files from default directory
    command: cp -r /etc/ansible/ /var/tmp/pssa/pssa-{{inventory_hostname}}
    ignore_errors: yes

  - name: pack up all collected data and remove collected files locally
    archive :
      path: /var/tmp/pssa/tmp/*
      dest: "/var/tmp/pssa-out.tar.gz"
      remove: yes

  - name: Copy pssa files to the scripts folder
    command: mv /var/tmp/pssa-out.tar.gz scripts/

- hosts:
  - nodes
  - etcd
  - glusterfs
  - glusterfs_registry
  gather_facts: no
  tasks:
  - name: check status of temporary directory on all hosts
    stat:
      path: /var/tmp/pssa
    register: temp_dir_stat
  - name: delete pssa directory on all hosts if exists
    file:
      path: /var/tmp/pssa
      state: absent
    when: temp_dir_stat.stat.exists == true 

- hosts:
  - localhost
  gather_facts: no
  tasks:
  - name: check status of temporary directory locally
    stat:
      path: /var/tmp/pssa
    register: temp_dir_stat
  - name: delete pssa directory locally if exists
    file:
      path: /var/tmp/pssa
      state: absent
    when: temp_dir_stat.stat.exists == true
